import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from "./GlobalProvider";
import Link from 'next/link';
import { CartProvider } from "../context/cartContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Profile.fyi Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          {/* <header className="bg-gray-800 p-4 text-white">
            <nav>
              <Link href="/">Home</Link> |{" "}
              <Link href="/cart">Cart  </Link>
            </nav>
          </header> */}
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
